#!/bin/bash

log="$1"
script='$5 ~ /solid/ { solid = 1 }
$5 ~ /fluid/ { solid = 0 }
solid && /^Min/ { print $10-273.15, $19-273.15  }'

if [ "$1" = "-h" ]; then
    echo "Usage: $(basename $0) [OPTIONS] LOGFILE" 2>&1
    echo "" 2>&1
    echo "Options:" 2>&1
    echo "    -h  Print help" 2>&1
    echo "" 2>&1
    exit 0
fi

old=$(du -b $log)
sleep 0.1
new=$(du -b $log)

offset=5000
[ "$old" = "$new" ] && offset=0

hist=$(awk '/^Time =/{n++} END{print n+'$offset'}' $log)
labels=$(awk '/^Create solid/{printf $6" max,"$6" min,"} /^\*/{exit 0}' $log)
nSolids=$(awk '/^Create solid/{n++} /^\*/{exit 0} END{print n*2}' $log)

fifo=/tmp/$(date | md5sum | head -c8)
mkfifo $fifo

tail -n+1 -f $log | awk -W interactive "$script" > $fifo &
pipe=$!
trend $fifo $hist -G 1x100 -gvd -geometry 800x480 \
    -L"$labels" -c${nSolids}a -t"Temperature in degC [0:$hist]"

kill $pipe
rm $fifo

exit 0
