#!/bin/bash

awkscript=/home/isack/OpenFOAM/scripts/resu.awk

old=$(du -b log/cht)
sleep 0.1
new=$(du -b log/cht)

if [ "$old" = "$new" ]; then
    histFactor=0
else
    histFactor=5000
fi

hist=$(awk '/^Time =/ {n++} END {print n+'$histFactor'}' log/cht)

labels=""
for arg in $@; do
    labels="$labels${arg} Ux,${arg} Uy,${arg} Uz,"
done

fifo=/tmp/$(date | md5sum | head -c8)
mkfifo $fifo

tail -n+1 -f log/cht | awk -f $awkscript -W interactive $@ > $fifo &
pipe=$!
trend $fifo $hist -G .1x100 -gvd -geometry 800x480 \
    -L"$labels" -c$(($#*3))a -t"Residuals in log(x) [0:$hist]"

kill $pipe
rm $fifo
