#!/bin/bash

log="$1"
fifo=/tmp/rplot-$(date | md5sum | head -c8)

if [ "$1" = "-h" ]; then
    echo "Usage: $(basename $0) [OPTIONS] LOGFILE" 2>&1
    echo "" 2>&1
    echo "Options:" 2>&1
    echo "    -h  Print help" 2>&1
    echo "" 2>&1
    exit 0
fi

old=$(du -b "$log")
sleep 0.5
new=$(du -b "$log")

offset=2
[ "$old" = "$new" ] && offset=1

hist=$(awk '/^Time =/{n++} END{print n*'$offset'}' "$log")
labels=$(awk '/^Create fluid/{printf $6" Ux,"$6" Uy,"$6" Uz,"} /^\*/{exit 0}' "$log")
nSolids=$(awk '/^Create fluid/{n++} /^\*/{exit 0} END{print n*3}' "$log")

mkfifo $fifo

tail -n+1 -f "$log" | awk -F"[ ,]+" -W interactive \
    '/U[xzy]/ {print log($8)/log(10)}' > $fifo &
pipe=$!
trend $fifo $hist -G 1x100 -gvd -geometry 800x480 \
    -L"$labels" -c${nSolids}a -t"Residuals in log(x) [0:$hist]"

kill $pipe
rm $fifo

exit 0
