#!/bin/bash

name=$1

awk '
BEGIN {
    print "# vtk DataFile Version 2.0"
    print "'$name'"
    print "ASCII"
    print "DATASET POLYDATA"
}
/^[0-9]/ {
    values[sprintf("%6f %6f %6f", $1, $2, $3)] = $4 " " $5 " " $6
}
/^v/ {
    point = sprintf("%6f %6f %6f", $2, $3, $4)
    points[nPoints++] = point
    field[nField++] = values[point]
}
/^f/ {
    faces[nFaces++] = "3 " $2-1 " " $3-1 " " $4-1
}
END {
    print "POINTS", nPoints, "float"
    for ( i=0; i<nPoints; i++  )
        print points[i]
    print "POLYGONS", nFaces, nFaces*4
    for ( i=0; i<nFaces; i++  )
        print faces[i]
    print "POINT_DATA", nPoints
    print "FIELD attributes 1"
    print "U 3", nPoints, "float"
    for ( i=0; i<nField; i++  )
        print field[i]
}
' postProcessing/sets/0.5/${name}_U.xy constant/triSurface/${name}.obj
