#!/bin/bash


awkscript=/home/isack/OpenFOAM/scripts/temp.awk
logfile=log/cht

if [ $# -gt 0 ]; then
    if [ "$1" = "-h" ]; then
        echo "" 2>&1
        echo "Usage: $(basename $0) [SOLID_REGION...]" 2>&1
        echo "" 2>&1
        exit 0
    fi
    solids=$@
else
    dict=system/includeDict
    if [ -e $dict ]; then
        solids=$(sed -ne 's/^ *solids[^(]*( \(.*\) );$/\1/p' $dict)
    else
        echo "" 2>&1
        echo "Dictionary $dict not found..." 2>&1
        echo "" 2>&1
        exit 1
    fi
fi

old=$(du -b $logfile)
sleep 0.1
new=$(du -b $logfile)

if [ "$old" = "$new" ]; then
    histFactor=0
else
    histFactor=5000
fi

hist=$(awk '/^Time =/ {n++} END {print n+'$histFactor'}' $logfile)

labels=""
nSolids=0
for solid in $solids; do
    labels="$labels${solid} min,${solid} max,"
    nSolids=$(($nSolids+1))
done

fifo=/tmp/$(date | md5sum | head -c8)
mkfifo $fifo

tail -n+1 -f $logfile | awk -f $awkscript -W interactive $solids > $fifo &
pipe=$!
trend $fifo $hist -G 1x100 -gvd -geometry 800x480 \
    -L"$labels" -c$(($nSolids*2))a -t"Temperature in degC [0:$hist]"

kill $pipe
rm $fifo

exit 0
