#!/bin/bash

#tail -n+1 -f log/cht | grep --line-buffered -A2 'ledj' | grep --line-buffered 'Min/max' | awk -W interactive '{print $10 }' | trend - 1000 -G 1x100 -SgFvd -geometry 800x480 -Lledj -tTemperature

mkfifo fifo

tail -n+1 -f log/cht | grep --line-buffered -A2 'ledj' | \
    grep --line-buffered 'Min/max' | awk -W interactive '{print $10 }' \
    > fifo &
    
trend fifo 1000 -G 1x100 -SgFvd -geometry 800x480 -Lledj -tTemperature
    
rm fifo
