#!/bin/bash


template=$HOME/OpenFOAM/template/region


#for dir in 0/[^F]*; do
#    test -d $dir || continue
#    solid=$(basename $dir)
#    echo "Setup region $solid"    
#    for folder in 0 constant system; do
#        for file in $template/$folder/SOLID/*; do
#            sed "s/SOLID/$solid/g" $file > $folder/$solid/$(basename $file)
#        done
#    done
#    changeDictionary -enableFunctionEntries -region $solid
#done

#for dir in 0/FLUID*; do
#    fluid=$(basename $dir)
#    echo "Setup region $fluid"  
#    for folder in 0 constant system; do
#        for file in $template/$folder/FLUID/*; do
#            sed "s/FLUID/$fluid/g" $file > $folder/$fluid/$(basename $file)
#        done
#    done
#    changeDictionary -enableFunctionEntries -region $solid
#done

for dir in 0/*; do
    test -d $dir || continue
    region=$(basename $dir)
    echo "Setup region $region"
    TYPE=$(test "${region::1}" = "F" && echo FLUID || echo SOLID)
    for folder in 0 constant system; do
        for file in $template/$folder/$TYPE/*; do
            sed "s/$TYPE/$region/g" $file > $folder/$region/$(basename $file)
        done
    done
    changeDictionary -enableFunctionEntries -region $region \
        > log/changeDictionary.$region.logfile
done


# ----------------------------------------------------------------- end-of-file
